# Generated by Django 4.2.1 on 2023-05-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitagoras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntos',
            name='ID_coordenadas',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
