# Generated by Django 4.2.1 on 2023-05-19 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('ID_mes', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('mes', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Semana',
            fields=[
                ('ID_dia', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=50)),
            ],
        ),
    ]
